<#
.SYNOPSIS
    Lumi: Architect - Forge Executor
    The execution layer that transforms Architecture Manifests into real system changes.

.DESCRIPTION
    This script reads a JSON manifest generated by the Brain module and executes
    the installation plan with full idempotency, Discovery phase, and detailed logging.

.PARAMETER ManifestPath
    Path to the Architecture Manifest JSON file.

.PARAMETER DryRun
    If specified, only simulates the execution without making real changes.

.EXAMPLE
    .\executor.ps1 -ManifestPath ".\output\manifest.json"
    
.EXAMPLE
    .\executor.ps1 -ManifestPath ".\output\manifest.json" -DryRun

.NOTES
    Author: Lumi: Architect
    Version: 1.0.0
    Requires: PowerShell 5.1+ or PowerShell 7+
    Requires: Administrator privileges for system-wide installations
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$ManifestPath,

    [Parameter(Mandatory = $false)]
    [switch]$DryRun,

    [Parameter(Mandatory = $false)]
    [switch]$SkipAdminCheck
)

# =============================================================================
# CONFIGURATION
# =============================================================================

$Script:Config = @{
    Version            = "1.0.0"
    LogTimestampFormat = "yyyy-MM-dd HH:mm:ss"
    AllowedCommands    = @("winget", "choco", "setx", "dotnet", "npm", "pip", "cargo", "git", "node", "python", "code")
    MaxRetries         = 2
    RetryDelaySeconds  = 5
}

# =============================================================================
# LOGGING FUNCTIONS
# =============================================================================

function Write-ForgeLog {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,
        
        [Parameter(Mandatory = $false)]
        [ValidateSet("Info", "Success", "Warning", "Error", "Skip", "Header")]
        [string]$Level = "Info"
    )
    
    $timestamp = Get-Date -Format $Script:Config.LogTimestampFormat
    $prefix = "[$timestamp]"
    
    switch ($Level) {
        "Header" {
            Write-Host ""
            Write-Host ("=" * 70) -ForegroundColor Cyan
            Write-Host "  $Message" -ForegroundColor Cyan
            Write-Host ("=" * 70) -ForegroundColor Cyan
        }
        "Success" {
            Write-Host "$prefix " -NoNewline -ForegroundColor DarkGray
            Write-Host "[OK] " -NoNewline -ForegroundColor Green
            Write-Host $Message -ForegroundColor Green
        }
        "Warning" {
            Write-Host "$prefix " -NoNewline -ForegroundColor DarkGray
            Write-Host "[WARN] " -NoNewline -ForegroundColor Yellow
            Write-Host $Message -ForegroundColor Yellow
        }
        "Error" {
            Write-Host "$prefix " -NoNewline -ForegroundColor DarkGray
            Write-Host "[FAIL] " -NoNewline -ForegroundColor Red
            Write-Host $Message -ForegroundColor Red
        }
        "Skip" {
            Write-Host "$prefix " -NoNewline -ForegroundColor DarkGray
            Write-Host "[SKIP] " -NoNewline -ForegroundColor Yellow
            Write-Host $Message -ForegroundColor Gray
        }
        "Info" {
            Write-Host "$prefix " -NoNewline -ForegroundColor DarkGray
            Write-Host "[INFO] " -NoNewline -ForegroundColor Blue
            Write-Host $Message -ForegroundColor White
        }
    }
}

function Write-ProgressBar {
    param(
        [int]$Current,
        [int]$Total,
        [string]$Activity
    )
    
    $percentComplete = [math]::Round(($Current / $Total) * 100)
    $barLength = 40
    $filledLength = [math]::Round($barLength * $Current / $Total)
    $bar = ("#" * $filledLength) + ("-" * ($barLength - $filledLength))
    
    Write-Host "  [$bar] $percentComplete% - $Activity" -ForegroundColor Cyan
}

# =============================================================================
# SECURITY VALIDATION
# =============================================================================

function Test-AdminPrivileges {
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal(
        [Security.Principal.WindowsIdentity]::GetCurrent()
    )
    return $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Test-CommandAllowed {
    param([string]$Command)
    
    $executable = ($Command -split " ")[0].ToLower()
    return $Script:Config.AllowedCommands -contains $executable
}

# =============================================================================
# DISCOVERY PHASE (IDEMPOTENCY)
# =============================================================================

function Test-PackageInstalled {
    param(
        [Parameter(Mandatory = $true)]
        [string]$VersionCheckCommand,
        
        [Parameter(Mandatory = $false)]
        [string]$PackageName = "Unknown"
    )
    
    $result = @{
        Installed = $false
        Version   = $null
        Output    = $null
    }
    
    if ([string]::IsNullOrWhiteSpace($VersionCheckCommand)) {
        Write-ForgeLog "No version_check_command for $PackageName, assuming not installed." -Level Warning
        return $result
    }
    
    # Security: Validate command before execution
    if (-not (Test-CommandAllowed -Command $VersionCheckCommand)) {
        Write-ForgeLog "Command not in allowed list: $VersionCheckCommand" -Level Warning
        return $result
    }
    
    try {
        $output = Invoke-Expression $VersionCheckCommand 2>&1
        $exitCode = $LASTEXITCODE
        
        if ($exitCode -eq 0 -or $null -eq $exitCode) {
            $result.Installed = $true
            $result.Output = $output | Out-String
            
            # Try to extract version number from output
            if ($result.Output -match "\d+\.\d+(\.\d+)?") {
                $result.Version = $Matches[0]
            }
        }
    }
    catch {
        $result.Installed = $false
    }
    
    return $result
}

# =============================================================================
# INSTALLATION FUNCTIONS
# =============================================================================

function Install-Package {
    param(
        [Parameter(Mandatory = $true)]
        [PSCustomObject]$Package,
        
        [Parameter(Mandatory = $false)]
        [switch]$DryRun
    )
    
    $result = @{
        Success  = $false
        Message  = ""
        ExitCode = -1
    }
    
    $packageManager = $Package.package_manager
    $packageId = $Package.package_id
    $flags = $Package.installation_flags -join " "
    
    switch ($packageManager) {
        "winget" {
            $installCommand = "winget install --id $packageId $flags --accept-source-agreements"
        }
        "choco" {
            $installCommand = "choco install $packageId $flags -y"
        }
        default {
            $result.Message = "Unknown package manager: $packageManager"
            return $result
        }
    }
    
    # Security Gate
    if (-not (Test-CommandAllowed -Command $installCommand)) {
        $result.Message = "Command blocked by Safety Gate: $installCommand"
        Write-ForgeLog $result.Message -Level Error
        return $result
    }
    
    if ($DryRun) {
        $result.Success = $true
        $result.Message = "[DRY RUN] Would execute: $installCommand"
        Write-ForgeLog $result.Message -Level Info
        return $result
    }
    
    # Execute installation with retry logic
    for ($attempt = 1; $attempt -le $Script:Config.MaxRetries; $attempt++) {
        Write-ForgeLog "Executing: $installCommand (Attempt $attempt/$($Script:Config.MaxRetries))" -Level Info
        
        try {
            $output = Invoke-Expression $installCommand 2>&1
            $exitCode = $LASTEXITCODE
            $result.ExitCode = $exitCode
            
            if ($exitCode -eq 0) {
                $result.Success = $true
                $result.Message = "Installation completed successfully."
                return $result
            }
            elseif ($exitCode -eq -1978335189) {
                $result.Success = $true
                $result.Message = "Package was already installed (detected by winget)."
                return $result
            }
            else {
                $result.Message = "Installation failed with exit code: $exitCode"
                if ($attempt -lt $Script:Config.MaxRetries) {
                    Write-ForgeLog "Retrying in $($Script:Config.RetryDelaySeconds) seconds..." -Level Warning
                    Start-Sleep -Seconds $Script:Config.RetryDelaySeconds
                }
            }
        }
        catch {
            $result.Message = "Exception during installation: $_"
            if ($attempt -lt $Script:Config.MaxRetries) {
                Start-Sleep -Seconds $Script:Config.RetryDelaySeconds
            }
        }
    }
    
    return $result
}

function Invoke-PostInstallCommands {
    param(
        [Parameter(Mandatory = $true)]
        [array]$Commands,
        
        [Parameter(Mandatory = $false)]
        [switch]$DryRun
    )
    
    Write-ForgeLog "POST-INSTALLATION COMMANDS" -Level Header
    
    $successCount = 0
    $failCount = 0
    
    foreach ($cmd in $Commands) {
        $command = $cmd.command
        $description = $cmd.description
        $isCritical = $cmd.is_critical -eq $true
        
        Write-ForgeLog "Running: $description" -Level Info
        
        if (-not (Test-CommandAllowed -Command $command)) {
            Write-ForgeLog "Command blocked by Safety Gate: $command" -Level Error
            if ($isCritical) {
                throw "Critical post-install command blocked. Aborting."
            }
            $failCount++
            continue
        }
        
        if ($DryRun) {
            Write-ForgeLog "[DRY RUN] Would execute: $command" -Level Info
            $successCount++
            continue
        }
        
        try {
            Invoke-Expression $command 2>&1 | Out-Null
            if ($LASTEXITCODE -eq 0 -or $null -eq $LASTEXITCODE) {
                Write-ForgeLog "Completed: $description" -Level Success
                $successCount++
            }
            else {
                Write-ForgeLog "Failed: $description (Exit code: $LASTEXITCODE)" -Level Error
                $failCount++
                if ($isCritical) {
                    throw "Critical command failed. Aborting Forge."
                }
            }
        }
        catch {
            Write-ForgeLog "Exception: $_" -Level Error
            $failCount++
            if ($isCritical) { throw }
        }
    }
    
    Write-ForgeLog "Post-install summary: $successCount succeeded, $failCount failed" -Level Info
}

# =============================================================================
# MAIN FORGE ORCHESTRATOR
# =============================================================================

function Start-Forge {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ManifestPath,
        
        [Parameter(Mandatory = $false)]
        [switch]$DryRun,
        
        [Parameter(Mandatory = $false)]
        [switch]$SkipAdminCheck
    )
    
    $startTime = Get-Date
    
    # =========================================================================
    # PHASE 0: INITIALIZATION
    # =========================================================================
    
    Write-Host ""
    Write-Host "  LUMI: ARCHITECT - FORGE EXECUTOR" -ForegroundColor Magenta
    Write-Host "  Version $($Script:Config.Version)" -ForegroundColor DarkGray
    Write-Host ""
    
    if ($DryRun) {
        Write-ForgeLog "DRY RUN MODE - No changes will be made to the system" -Level Warning
    }
    
    # =========================================================================
    # PHASE 1: ADMIN PRIVILEGE CHECK
    # =========================================================================
    
    Write-ForgeLog "PRIVILEGE VALIDATION" -Level Header
    
    if (-not $SkipAdminCheck) {
        if (Test-AdminPrivileges) {
            Write-ForgeLog "Running with Administrator privileges." -Level Success
        }
        else {
            Write-ForgeLog "This script requires Administrator privileges for system-wide installations." -Level Error
            Write-ForgeLog "Please run PowerShell as Administrator and try again." -Level Error
            Write-Host ""
            Write-Host "  To elevate, run:" -ForegroundColor Yellow
            Write-Host "  Start-Process powershell -Verb RunAs" -ForegroundColor Cyan
            Write-Host ""
            return @{ Success = $false; Reason = "Insufficient privileges" }
        }
    }
    else {
        Write-ForgeLog "Admin check skipped by user request." -Level Warning
    }
    
    # =========================================================================
    # PHASE 2: MANIFEST LOADING & VALIDATION
    # =========================================================================
    
    Write-ForgeLog "LOADING MANIFEST" -Level Header
    Write-ForgeLog "Reading: $ManifestPath" -Level Info
    
    try {
        $manifestContent = Get-Content -Path $ManifestPath -Raw -Encoding UTF8
        $manifest = $manifestContent | ConvertFrom-Json
        
        Write-ForgeLog "Manifest Version: $($manifest.manifest_version)" -Level Success
        Write-ForgeLog "Target Environment: $($manifest.target_environment.name)" -Level Info
        Write-ForgeLog "Description: $($manifest.target_environment.description)" -Level Info
        Write-ForgeLog "Packages to process: $($manifest.packages.Count)" -Level Info
    }
    catch {
        Write-ForgeLog "Failed to parse manifest: $_" -Level Error
        return @{ Success = $false; Reason = "Invalid manifest JSON" }
    }
    
    # =========================================================================
    # PHASE 3: PACKAGE INSTALLATION LOOP
    # =========================================================================
    
    Write-ForgeLog "PACKAGE INSTALLATION" -Level Header
    
    $sortedPackages = $manifest.packages | Sort-Object -Property priority_level
    
    $totalPackages = $sortedPackages.Count
    $installedCount = 0
    $skippedCount = 0
    $failedCount = 0
    $currentIndex = 0
    
    foreach ($package in $sortedPackages) {
        $currentIndex++
        $displayName = $package.display_name
        $packageId = $package.package_id
        $isCritical = $package.is_critical -eq $true
        
        Write-Host ""
        Write-ForgeLog "[$currentIndex/$totalPackages] Processing: $displayName ($packageId)" -Level Info
        Write-ForgeLog "Priority: $($package.priority_level) | Critical: $isCritical | Manager: $($package.package_manager)" -Level Info
        
        # DISCOVERY PHASE
        $versionCheck = $package.version_check_command
        $discoveryResult = Test-PackageInstalled -VersionCheckCommand $versionCheck -PackageName $displayName
        
        if ($discoveryResult.Installed) {
            $versionInfo = ""
            if ($discoveryResult.Version) {
                $versionInfo = " (v$($discoveryResult.Version))"
            }
            Write-ForgeLog "$displayName is already installed$versionInfo. Skipping." -Level Skip
            $skippedCount++
            continue
        }
        
        # INSTALLATION PHASE
        $installResult = Install-Package -Package $package -DryRun:$DryRun
        
        if ($installResult.Success) {
            Write-ForgeLog "$displayName installed successfully!" -Level Success
            $installedCount++
        }
        else {
            Write-ForgeLog "Failed to install $displayName : $($installResult.Message)" -Level Error
            $failedCount++
            
            if ($isCritical) {
                Write-ForgeLog "CRITICAL PACKAGE FAILED - Aborting Forge." -Level Error
                return @{
                    Success   = $false
                    Reason    = "Critical package installation failed: $displayName"
                    Installed = $installedCount
                    Skipped   = $skippedCount
                    Failed    = $failedCount
                }
            }
        }
        
        Write-ProgressBar -Current $currentIndex -Total $totalPackages -Activity $displayName
    }
    
    # =========================================================================
    # PHASE 4: POST-INSTALLATION COMMANDS
    # =========================================================================
    
    if ($manifest.post_install_commands -and $manifest.post_install_commands.Count -gt 0) {
        Invoke-PostInstallCommands -Commands $manifest.post_install_commands -DryRun:$DryRun
    }
    
    # =========================================================================
    # PHASE 5: SUMMARY
    # =========================================================================
    
    $endTime = Get-Date
    $duration = $endTime - $startTime
    $durationStr = "{0:D2}:{1:D2}" -f $duration.Minutes, $duration.Seconds
    
    Write-ForgeLog "FORGE COMPLETE" -Level Header
    Write-Host ""
    Write-Host "  +------------------------------------------+" -ForegroundColor Green
    Write-Host "  |         FORGE EXECUTION SUMMARY         |" -ForegroundColor Green
    Write-Host "  +------------------------------------------+" -ForegroundColor Green
    Write-Host "  |  Installed:  $installedCount packages" -ForegroundColor White
    Write-Host "  |  Skipped:    $skippedCount packages (already exist)" -ForegroundColor Yellow
    Write-Host "  |  Failed:     $failedCount packages" -ForegroundColor $(if ($failedCount -gt 0) { "Red" } else { "White" })
    Write-Host "  |  Duration:   $durationStr minutes" -ForegroundColor White
    Write-Host "  +------------------------------------------+" -ForegroundColor Green
    Write-Host ""
    
    if ($failedCount -eq 0) {
        Write-ForgeLog "All operations completed successfully!" -Level Success
    }
    else {
        Write-ForgeLog "$failedCount package(s) failed. Check logs above for details." -Level Warning
    }
    
    return @{
        Success   = ($failedCount -eq 0)
        Installed = $installedCount
        Skipped   = $skippedCount
        Failed    = $failedCount
        Duration  = $duration
    }
}

# =============================================================================
# SCRIPT ENTRY POINT
# =============================================================================

$result = Start-Forge -ManifestPath $ManifestPath -DryRun:$DryRun -SkipAdminCheck:$SkipAdminCheck

if ($result.Success) {
    exit 0
}
else {
    exit 1
}
